<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        function squareRoot(number){

            if(number<0){
                throw new Error("Sorry, can't calculate square root of a negative number.");
               }else{
                return Math.sqrt(number);
               }
        }

        try{
            squareRoot(16);
            squareRoot(625);
            squareRoot(100);   
            squareRoot(-64);
        
            alert("All calculations are performed successfully.");
            document.write(squareRoot(16)+"<br>");
            document.write(squareRoot(625)+"<br>");
            document.write(squareRoot(100));
            document.write(squareRoot(-64)+"<br>"); // as per our loop mention in function... we can't find squareroot of negative number....so catch part will generate error...

        }catch(e){
            alert(e.message);
        }
    </script>
</body>
</html>